import "./globals.css";
import MainLayout from "@/layout/MainLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body>
     <MainLayout>
      {children}
     </MainLayout>
      
      </body>
    </html>
  );
}
